function m(b,a,c,d){b.o.lb(b.rb,a,c,d)}function n(b,a,c,d){b.o.da?m(b,a,c,d):b.o.Pe()._OnMessageFromDOM({type:"event",component:b.rb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.o.B(b.rb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Ub||(b.o.xc(b.fe),b.Ub=!0)}window.fb=class{constructor(b,a){this.o=b;this.rb=a;this.Ub=!1;this.fe=()=>this.Ca()}jd(){}Ca(){}};
window.Cf=class{constructor(){this.ed=-1}j(){-1!==this.ed&&(self.clearTimeout(this.ed),this.ed=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Sa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Sb}
window.nd=class extends self.fb{constructor(b,a){super(b,a);this.Sa=new Map;this.pb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.pb&&d.parentElement.removeChild(d);this.Sa.delete(c)}],["set-visible",c=>{if(this.pb){var d=this.Sa.get(c.elementId),e=d.Sb;d.Od?e.style.display=c.isVisible?"":"none":d.hf=!!c.isVisible}}],["update-position",c=>{if(this.pb){var d=this.Sa.get(c.elementId),e=d.Sb,f=this.o;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.nf=g;g=f.pd(g);g!==d.Fa&&(e.remove(),f.qc(g).appendChild(e),d.Fa=g,f.Gc());c=c.htmlZIndex;c!==d.Oc&&(d.Oc=c,f.Gc());d.Od||(d.Od=!0,d.hf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.sf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.wf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,ia=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const la=new Set(["cordova","playable-ad","instant-games"]);let ma=!1;
window.mb=class b{constructor(a){this.da=a.yf;this.wa=null;this.aa="";this.$a=a.vf;this.Hb={};this.Ua=this.ta=null;this.Ra=[];this.ma=null;this.Sd=!0;this.M=[];this.Zc=[];this.$c=!1;this.ge=()=>this.Ne();this.Qc=!1;this.Ld=0;this.wb=null;this.Za=-1;this.mf=()=>this.Ye();this.Eb=new Set;this.fd=null;this.he=[];this.A=a.ie;this.Vb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.Ad(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Ad(c));this.Yb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.bf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Te());this.B("runtime","cordova-fetch-local-file",c=>this.Ue(c));this.B("runtime","create-job-worker",()=>this.Ve());this.B("runtime","send-wrapper-extension-message",c=>this.af(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.yd(a)):this.yd(a)}j(){this.yc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ua&&(this.Ua.j(),this.Ua=null);for(const {canvas:a,
cb:c}of this.M)a.remove(),c.remove();this.M.length=0}qd(){return this.M[0].canvas}pd(a){return Math.min(a,this.M.length-1)}qc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].cb}De(){return ba&&"cordova"===this.A}jb(){const a=navigator.userAgent;return ba&&la.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Be(){return y}rd(){return y&&la.has(this.A)}td(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ma(){return this.td()||"xbox-uwp-webview2"===this.A}async yd(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.A?this.nb({type:"ready"}):this.Ma()&&(this.df(),this.he=(await this.Se()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.Yb={};await this.Ke();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Yb.hasOwnProperty(c)?a.bb[d]={sf:!0,wf:this.Yb[c]}:this.qa.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.qa[c]))}a.mc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.xc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.uf?this.aa=a.uf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Af&&(this.Hb=a.Af);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Xe(d));this.wb=
new self.Ee(this);await pa(this.wb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Re(a,c.port2):await this.Qe(a,c.port2)}Ac(a){a=this.Hb.hasOwnProperty(a)?this.Hb[a]:a.endsWith("/workermain.js")&&this.Hb.hasOwnProperty("workermain.js")?this.Hb["workermain.js"]:"playable-ad"===
this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Vb)return a=await this.Jb(d.rf?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}xd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.ib(),k=a.Ff,l=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ie;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.wb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Ef,jobScheduler:{inputPort:A.Pc,outputPort:A.Yc,maxNumWorkers:A.jf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$a+"opus.wasm.wasm",isFileProtocol:this.Vb,isiOSCordova:this.De(),isiOSWebView:this.jb(),isWindowsWebView2:this.td(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.he,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Re(a,c){const d=this.Ac(a.zf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.oc(d,this.aa,{type:"module",name:"Runtime",rf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,cb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.mc||[],k=a.bb;h=await Promise.all(h.map(l=>this.Oa(l)));k=await Promise.all(k.map(l=>this.Oa(l)));if("cordova"===this.A)for(let l=0,p=a.lc.length;l<p;++l){const r=
a.lc[l],t=r[0];if(t===a.gd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Oa(t)}this.ta.postMessage(Object.assign(this.xd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.lc,mainProjectScript:a.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...qa(this.wb)]);this.Ra=F.map(l=>new l(this));this.wd();ra(e);sa(g);ta(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.o.ud(r.rb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.lb("runtime","go-to-last-error-script"))}async Qe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,cb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ra=F.map(h=>new h(this));this.wd();ra(d);sa(e);e=a.bb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.mc)){var f=[...a.mc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Oa(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.gd;const g=a.lc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Oa(k),await z(k),"preview"!==this.A||e[h]||this.Cd(h,"main script did not run to completion")}catch(l){this.Cd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Oa(k),await z(k);"preview"===this.A&&"object"!==typeof self.Bf.Df?(this.Ob(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.xd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ka}),ta(this.ma),this.zd(),this.Ua=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ua,
a))}Cd(a,c){this.Ob();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}zd(){this.Ob()}Ob(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ve(){const a=await ua(this.wb);return{outputPort:a,transferables:[a]}}bf(a){if(!this.Qc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,cb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Sd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Sd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,cb:p}=this.M.pop();p.remove();this.da&&!d?this.Zc.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ra(c),sa(d),this.M.push({canvas:c,cb:d});for(const l of this.Ra)if(l instanceof window.nd&&l.pb)for(const p of l.Sa.values())e=l.o.pd(p.nf),f=p.Fa,-1!==e&&-1!==f&&e!==f&&(f=p.Sb,f.remove(),l.o.qc(e).appendChild(f),p.Fa=e);this.Gc();return{addedCanvases:a,transferables:k}}Te(){for(const a of this.Zc)a.remove();this.Zc.length=0}Gc(){this.$c||(this.$c=!0,this.xc(this.ge))}Ne(){this.Bd(this.ge);
this.$c=!1;let a=[];for(var c of this.Ra)if(c instanceof window.nd){var d=c.pb?[...c.Sa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Fa,l=h.Fa;return k!==l?k-l:g.Oc-h.Oc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Fa!==c&&(this.vd(c,a.slice(d,e)),c=g.Fa,d=e)}d<e&&this.vd(c,a.slice(d,e))}vd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Sb);var d=new Set(c);a=this.qc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Pe(){if(this.da)throw Error("not available in worker mode");return this.Ua}lb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ud(a,c,d,e,f){const g=ja++,h=new Promise((k,l)=>{ia.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.We(a);if("result"===c)this.Ze(a);else if("runtime-ready"===c)this.$e();else if("alert-error"===c)this.Ob(),alert(a.message);else if("creating-runtime"===c)this.zd();else throw Error(`unknown message '${c}'`);}We(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Nb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Nb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Nb(f,!1,""+h)}):this.Nb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Nb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ze(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ia.get(c);d?e.resolve(a):e.reject(a);ia.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,
e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ib(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}wd(){for(const a of this.Ra)if("runtime"===a.rb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Xe(a){this.lb("debugger","message",a)}$e(){for(const a of this.Ra)a.jd()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ma)}static Dd(a){ma=!!a}xc(a){this.Eb.add(a);
this.Fc()}Bd(a){this.Eb.delete(a);0===this.Eb.size&&this.yc()}Fc(){-1===this.Za&&0<this.Eb.size&&(this.Za=requestAnimationFrame(this.mf))}yc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Ye(){this.Za=-1;for(const a of this.Eb)a();this.Fc()}Da(a){this.ma.Da(a)}Na(a){this.ma.Na(a)}Ec(){this.ma.Ec()}Mb(a){this.ma.Mb(a)}Ce(){return!!ea["audio/webm; codecs=opus"]}async ef(a){a=await this.ud("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ge(a){this.Qc=!0;this.Ld=
a}Ae(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}sd(a){return!this.Ae(a)}async Oa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Vb&&this.sd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Jb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ue(a){const c=a.filename;switch(a.as){case "text":return await this.ze(c);case "buffer":return await this.Jb(c);default:throw Error("unsupported type");
}}md(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ze(a){a=await this.md(a);return await fa(a)}zc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.Le(a.filename,a.xf,a.qf)}}Jb(a){return new Promise((c,d)=>{C.push({filename:a,xf:e=>{E--;this.zc();c(e)},qf:e=>{E--;this.zc();d(e)}});this.zc()})}async Le(a,c,d){try{const e=await this.md(a),f=await ha(e);c(f)}catch(e){d(e)}}Ad(a){if("entered-fullscreen"===
a)b.Dd(!0),H(this.ma);else if("exited-fullscreen"===a)b.Dd(!1),H(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.fd(a),this.fd=null):"extension-message"===c?this.lb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}af(a){this.nb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}nb(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}df(){window.moveTo=(a,c)=>{this.nb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.nb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Se(){return this.Ma()?new Promise(a=>{this.fd=a;this.nb({type:"wrapper-init"})}):Promise.resolve()}async Ke(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.Je(c,d));
await Promise.all(a)}async Je(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Oe(c);d||(d=this.Me(c));this.qa[a]=d}}async Oe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Me(a){a=this.cf(a);return this.Ie(a.data,
a.tf)}cf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{tf:a,data:d}}Ie(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const I=self.mb,va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},xa={dispatchRuntimeEvent:!0};function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function K(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ca(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function ra(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function sa(b){b.addEventListener("selectstart",Fa);b.addEventListener("gesturehold",Fa);b.addEventListener("touchstart",Fa)}function ta(b){b.Kd=!0;b.Uc=b.o.oa();b.xb=b.o.ga()}
function H(b){if(!b.ka){var a=I.ib();a&&"any"!==b.cd&&Ia(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.Jd=!0},1E3);"cordova"===b.o.A?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.bc=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.bc}}
function Pa(b){b.Fd||(b.Fd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Qa(b){b.Ed||(b.Ed=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Ra(b){await ya(b.url)}
function Sa(b,a){b.Md=a.message;-1===b.Kc&&(b.Kc=setTimeout(()=>{b.Kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Md)},250))}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.ib(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Oa(b,a){b.bc!==a&&((b.bc=a)?b.o.yc():b.o.Fc(),m(b,"visibilitychange",{hidden:a}),!a&&b.o.jb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ua(b,a,c){"Backspace"===c.key&&L(c);if(b.o.Ma()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=va.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J))}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Wc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.Wc=c.buttons)}}function Va(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Wa(b,a,c,d){const e=b.oa(),f=b.ga();b.ab=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()}):10>d&&Xa(b,e,f,d+1)}function Xa(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>Wa(b,a,c,d),48)}
function Ia(b){b=b.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Ib(class extends self.fb{constructor(b){super(b,"runtime");this.Kd=!1;this.ab=-1;this.cd="any";this.bc=this.Ed=this.Fd=!1;this.ic=document.createElement("div");this.ic.className="c3-screen-reader-text";this.ic.setAttribute("aria-live","polite");document.body.appendChild(this.ic);this.Ha=null;this.ka=!1;this.Md="";this.Kc=-1;this.Jd=!1;this.Uc=b.oa();this.xb=b.ga();this.za=this.Gb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ja(c));b.B("runtime","raster-svg-image",c=>Ka(c));b.B("runtime","get-svg-image-size",c=>La(c));b.B("runtime","set-target-orientation",c=>{this.cd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ma(c));b.B("runtime","go-to-script",c=>Ma(c));b.B("runtime","before-start-ticking",()=>Na(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var d=this.Ha;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ha&&(this.Ha.style.display="none")});b.B("runtime","enable-device-orientation",()=>Pa(this));b.B("runtime","enable-device-motion",()=>Qa(this));b.B("runtime","add-stylesheet",c=>Ra(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.ic.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.o.qd().style.display="";this.o.Ge(c.duration)});b.B("runtime","export-to-video-progress",c=>Sa(this,c));b.B("runtime","exported-to-video",c=>{window.pf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.pf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ca(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.Wc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Kd){var c=this.oa();var d=this.ga();if(this.o.rd()){if(this.Jd){if(this.Uc===
c&&d<this.xb){this.Gb=this.xb-d;Va(this,this.xb,this.Gb);c=void 0;break a}0<this.Gb&&(this.Gb=0,Va(this,d,this.Gb))}this.Uc=c;this.xb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()});this.o.jb()&&(-1!==this.ab&&clearTimeout(this.ab),Wa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",c=>Ta(this,c));window.addEventListener("webkitfullscreenerror",c=>Ta(this,c));window.addEventListener("mozfullscreenerror",c=>Ta(this,c));if(b.jb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ca(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Va=new Set;this.$b=new WeakSet;this.va=!1}jd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,xa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},xa);this.Wc=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ca(a))&&m(this,"keyboard-blur",null,xa)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,wa));window.addEventListener("mousemove",a=>M(this,"mousemove",a,wa));window.addEventListener("mouseup",a=>M(this,"mouseup",a,wa));window.addEventListener("dblclick",
a=>M(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ya(a.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.o.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Ec();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.o.Be()&&!this.o.rd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.o.jb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.o.oa()}ga(){return this.o.ga()}Ec(){var b=[...this.Va];this.Va.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Va.add(a)})}Da(b){if("function"!==
typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Va.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Va.add(b)})}Na(b){this.Va.delete(b);this.$b.add(b)}Mb(b){this.va=!!b}});"use strict";
async function pa(b){if(b.ff)throw Error("already initialised");b.ff=!0;var a=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.$a:"")+"dispatchworker.js");b.Jc=await b.xa.oc(a,b.qb,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await ua(b)}function qa(b){return[b.Pc,b.Yc]}
async function ua(b){const a=b.Ud.length;var c=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.$a:"")+"jobworker.js");c=await b.xa.oc(c,b.qb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ud.push(c);return e.port1}
self.Ee=class{constructor(b){this.xa=b;this.qb=b.aa;this.qb="preview"===b.A?this.qb+"workers/":this.qb+b.$a;this.jf=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Ud=[];this.Yc=this.Pc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.mb({yf:!0,zf:"workermain.js",bb:["scripts/c3runtime.js"],lc:[],gd:"",vf:"scripts/",mc:[],ie:"html5"}));"use strict";let Za=!1;
async function $a(b){var a=ab(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function O(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Za||(console.warn("[Construct] Failed to access gamepads: ",b),Za=!0),[]}}
function ab(b){for(const a of O())if(a.index===b)return a;return null}
self.mb.Ib(class extends self.fb{constructor(b){super(b,"gamepad");this.Td=!!navigator.getGamepads;this.Sc=!1;q(this,"is-supported",()=>this.Td);q(this,"ready",()=>{this.Sc=!0;for(const a of O())m(this,"gamepad-connected",{index:a.index,id:a.id});this.Td&&w(this)});q(this,"vibrate",a=>$a(a));q(this,"reset-vibrate",a=>{(a=ab(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Sc&&(a=a.gamepad,m(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Sc&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of O()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}Ca(){var b=O();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),m(this,"input-update",b))}});"use strict";
self.mb.Ib(class extends self.fb{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.qd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const bb=180/Math.PI;
async function cb(b,a){if(a.isiOSCordova||a.isSafari)b.dc=!0;b.dd=a.timeScaleMode;b.Zd=["equalpower","HRTF","soundfield"][a.panningModel];b.Id=["linear","inverse","exponential"][a.distanceModel];b.$d=a.refDistance;b.Yd=a.maxDistance;b.be=a.rolloffFactor;if(b.o.Qc)b.dc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Ld)});else{var c={latencyHint:a.latencyHint};b.ee||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");db(b);b.g.onstatechange=()=>{"running"!==b.g.state&&db(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function gb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Vd=g.slice(0);hb(b,g);try{b.R=await ib(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,na=p.outerAngle,oa=p.outerGain;if(u.vb){jb(u,p.x,p.y,p.z,p.angle);var D=self.eb.He;u.ra[0]!==D(A)&&
(u.ra[0]=D(A),u.F.coneInnerAngle=D(A));u.ra[1]!==D(na)&&(u.ra[1]=D(na),u.F.coneOuterAngle=D(na));u.ra[2]!==oa&&(u.ra[2]=oa,u.F.coneOuterGain=oa)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),kb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=g.join(" ");d=b.Db.get(c);if(!d)throw Error("expected pending tag");d.hd--;0===d.hd&&(d.resolve(),b.Db.delete(c))}w(b)}
async function lb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const h of S(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ta=g;h.de=a}T(b)}async function ob(b,a){const c=a.tags;a=a.rate;await nb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ea())}async function pb(b,a){const c=a.tags;a=a.pos;await nb(b,c);for(const d of S(b,c))d.uc(a)}
async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function sb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.oe(b,...e);else if("delay"===c)d=new self.me(b,...e);else if("convolution"===c){var g=d=new self.le(b,f.ha,...e),h=a.bufferType;g.Gd=a.bufferOriginalUrl;g.Hd=h}else if("flanger"===c)d=
new self.pe(b,...e);else if("phaser"===c)d=new self.re(b,...e);else if("gain"===c)d=new self.qe(b,...e);else if("stereopan"===c)d=new self.te(b,...e);else if("tremolo"===c)d=new self.ue(b,...e);else if("ringmod"===c)d=new self.se(b,...e);else if("distortion"===c)d=new self.ne(b,...e);else if("compressor"===c)d=new self.ke(b,...e);else if("analyser"===c)d=new self.je(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Rd=l.length;d.bd=
h;l.push(d);tb(g,h)}ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.jc=a.timeScale;b.Lc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.va=a.isSilent;b.o.Mb(b.va);b.Zb=a.masterVolume;b.Qa.gain.value=
b.Zb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>sb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>wb(b,f,c)));T(b)}
async function yb(b,a){try{const c=b.g.suspend(a.time);b.Qd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.lb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>zb(d)),b.Qd=!0);await c}catch(c){zb(c)}}
function db(b){b.Tb||(b.Nc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Tb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.hb()===c)return await Ab(g),g;if(f)return null;if(e&&(b.dc||b.Pd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ee;e&&f&&(b.Pd=!0);c=!e||b.dc||f?new self.xe(b,a,c,d,e,f):new self.ve(b,a,c,d,e);b.ia.push(c);await Ab(c);b.Xd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Xd.add(a));return c}
function Bb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Cb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function tb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Db(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Vc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Db(b,a){if(a)for(const c of b.H)Bb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Eb(b,a,c){return c?b.o.ef(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Bb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ib(b,a,c,d,e,f){for(const g of b.H)if(g.hb()===c&&(g.nc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Hc?new self.we(a.u,a,e):new self.ye(a.u,a,e);b.H.push(e);return e}
function hb(b,a){a=a.join(" ");let c=b.Db.get(a);if(!c){let d=null;c={hd:0,promise:new Promise(e=>d=e),resolve:d};b.Db.set(a,c)}c.hd++}function nb(b,a){return(b=b.Db.get((0===a.length?b.Vd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Pa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Gb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function ub(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.gb());m(b,"fxstate",{fxstate:a});b.Rc=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],f=d.orient,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],e.setPosition(...b.Xa),e.setOrientation(...b.Wa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),kb(b,d));c.Play(k,l,p,0);a.isPlaying||c.kb();c.Cc(a)}}}function zb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.fb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Tb=this.Nc=!1;this.ya=()=>{if(!this.Nc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Tb&&(this.Nc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Tb=!1)}};this.ia=[];this.H=[];this.R=null;this.Vd=[];this.Xd=new Set;this.Wd=-1;this.Db=new Map;this.Zb=1;this.va=!1;this.dd=0;this.jc=1;this.Lc=0;this.Zd="HRTF";this.Id="inverse";this.$d=600;this.Yd=1E4;this.be=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Pd=this.dc=!1;this.ee=this.o.Ce();this.ja=new Map;this.Pa=new Set;this.Qd=this.Rc=!1;this.Vc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Vc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Cb(this,this.Vc))};this.Rb=null;self.C3Audio_GetOutputStream=()=>{this.Rb||(this.Rb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Rb));return this.Rb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>cb(this,a)],["play",a=>gb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.kb():d.Lb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>lb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Qa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ib(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.o.Mb(this.va);for(const c of this.H)c.Pb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.vc(a)}],["set-playback-rate",a=>ob(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),kb(d,a)}],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);ub(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);tb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Lc=a.gameTime;this.Wd=a.tickCount;if(0!==this.dd)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&jb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>yb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Kb(){return this.va}Da(b){this.o.Da(b)}Na(b){this.o.Na(b)}Ca(){for(var b of this.Pa)b.Ca();
b=this.g.currentTime;for(var a of this.H)a.Ca(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.gb());m(this,"state",{tickCount:this.Wd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.bd,index:c.Rd,peak:c.Ya,rms:c.ae,binCount:c.l.frequencyBinCount,freqBins:c.Nd}))});0===a.length&&0===this.Pa.size&&this.Ub&&(this.o.Bd(this.fe),this.Ub=!1)}static He(b){return b*bb}static od(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Fe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.mb.Ib(self.eb);"use strict";function Ab(b){b.Xb||(b.Xb=b.Bc());return b.Xb}self.kd=class{constructor(b,a,c,d,e){this.u=b;this.lf=a;this.Ja=c;this.T=d;this.gf=e;this.Hc="";this.Xb=null}j(){this.Xb=this.u=null}Bc(){}V(){return this.u.V()}rc(){return this.lf}hb(){return this.Ja}pc(){return this.T}Aa(){return this.gf}fa(){}};"use strict";
self.ve=class extends self.kd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.yb=this.zb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Cb=this.V().createGain();this.Bb=null;this.L.addEventListener("canplay",()=>{this.zb&&(this.zb(),this.yb=this.zb=null);!this.Bb&&this.L&&(this.Bb=this.V().createMediaElementSource(this.L),this.Bb.connect(this.Cb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.yb&&(this.yb(f),this.yb=this.zb=null)})}j(){Fb(this.u,this);this.Cb.disconnect();this.Cb=null;this.Bb.disconnect();this.Bb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Bc(){return new Promise((b,a)=>{this.zb=b;this.yb=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Jb(b){if(b.Ga)return b.Ga;var a=b.u.o;if("cordova"===a.A&&a.sd(b.Ja)&&a.Vb)b.Ga=await a.Jb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Kb(b){if(b.ha)return b.ha;b.ha=await Eb(b.u,b.Ga,b.kf);b.Ga=null}
self.xe=class extends self.kd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ha=this.Ga=null;this.kf=!!f}j(){Fb(this.u,this);this.ha=this.Ga=null;super.j()}async Bc(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.vb!==a&&(b.vb=a,b.vb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Zd,b.F.distanceModel=b.u.Id,b.F.refDistance=b.u.$d,b.F.maxDistance=b.u.Yd,b.F.rolloffFactor=b.u.be),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Wb!==a&&(b.Wb=a,b.Wb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function kb(b,a){b.Wb&&b.ad!==a&&(b.ca.pan.value=a,b.ad=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ta=-1;b.G.gain.value=b.sc()}function Ib(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Pb())}
function jb(b,a,c,d,e){if(b.vb){var f=b.Xa,g=b.Wa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Tc?b.u.Lc:performance.now()/1E3}
self.ld=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Qb=Lb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.vb=!1;this.Xa=[0,0,0];this.Wa=[0,0,0];this.ra=[0,0,0];this.ca=null;this.Wb=!1;this.ad=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ka=1;this.ua=!1;this.la=1;b=this.u.dd;this.Tc=1===b&&!this.Aa()||2===b;this.Ta=this.pa=-1;this.de=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Cb(this.u,0<this.na.length?this.na[0]:"")}rc(){return this.P.rc()}hb(){return this.P.hb()}pc(){return this.P.pc()}Aa(){return this.P.Aa()}O(){}nc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}fa(){return this.P.fa()}Play(){}Ba(){}kb(){}Lb(){}Ca(b){-1!==this.Ta&&b>=this.Ta&&(this.Ta=-1,this.de&&this.Ba(),Gb(this.u,"fade-ended",this.na,this.Qb))}sc(){const b=this.Ka;return isFinite(b)?b:0}Kb(){return this.u.Kb()}Pb(){}vc(){}Ea(){}uc(){}wc(){}tc(){}gb(){var b=
this.Qb,a=this.na,c=this.fa(),d=-1===this.Ta?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Xa,orient:this.Wa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.rc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.tc(),pan:f,stereoPan:this.ca?
this.ad:null}}Cc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ea());Ib(this,b.isMuted)}};"use strict";
self.we=class extends self.ld{constructor(b,a,c){super(b,a,c);this.P.Cb.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Ba();this.P.Cb.disconnect();super.j()}W(){return this.P.W()}Dc(){this.I=!0;this.pa=-1;Gb(this.u,"ended",this.na,this.Qb)}O(){return this.W().ended}nc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.hb()}' to position '${c}': `,e)}this.u.Da(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.pa=-1}kb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Lb(){!this.J||this.I||this.O()||(this.u.Da(this.W()),this.J=!1)}Pb(){this.W().muted=this.ua||this.Kb()}vc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ea(){let b=this.la;this.Tc&&(b*=this.u.jc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}tc(){return this.La()}wc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Da(this.W()),this.sa=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.ob=null}
self.ye=class extends self.ld{constructor(b,a,c){super(b,a,c);this.s=null;this.ac=d=>this.Dc(d);this.Mc=!0;this.ob=null;this.S=this.cc=this.ec=0;this.Xc=1}j(){this.Ba();W(this);this.ac=null;super.j()}Dc(b){this.J||this.sa||b.target!==this.ob||(this.I=this.Mc=!0,this.pa=-1,W(this),Gb(this.u,"ended",this.na,this.Qb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Mc}nc(){return!this.s||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.cc+(V(this)-this.ec)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Xc=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.ob=this.s;this.s.onended=this.ac;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Mc=!1;this.Y=b;this.la=1;this.ec=V(this);this.cc=c}Ba(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}kb(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Lb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.ac,this.s.loop=this.Y,U(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=V(this),this.cc=this.S,this.J=!1)}sc(){return super.sc()*this.Xc}Pb(){this.Xc=this.ua||this.Kb()?0:1;U(this,this.Ka)}vc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ea(){let b=this.la;this.Tc&&(b*=this.u.jc);this.s&&(this.s.playbackRate.value=b)}uc(b){this.I||this.O()||(this.J?this.S=b:(this.kb(),
this.S=b,this.Lb()))}tc(){return this.S}wc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.La(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.sa=!1:this.sa&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.ac,this.s.loop=this.Y,U(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=V(this),this.cc=this.S,this.sa=!1)}Cc(b){super.Cc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Rd=-1;this.T=this.bd="";this.m=null}j(){this.g=null}N(){}U(){}gb(){return{type:this.T,tag:this.bd,params:this.m}}}
self.oe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.me=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Ab=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.tb=X(this);this.tb.gain.value=c;this.v.connect(this.Ab);this.v.connect(this.h);this.Ab.connect(this.i);this.Ab.connect(this.X);this.X.connect(this.tb);this.tb.connect(this.Ab)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Ab.disconnect();
this.X.disconnect();this.tb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.eb.od;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.tb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Hd=this.Gd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.sb=this.g.createConvolver();this.sb.normalize=c;this.sb.buffer=a;this.v.connect(this.sb);this.v.connect(this.h);this.sb.connect(this.i)}j(){this.v.disconnect();this.sb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.Gd;b.bufferUrl="";b.bufferType=this.Hd;return b}};
self.pe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ub=X(this);this.ub.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.ub);this.ub.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ub.gain,a/100,c,d)}}};
self.re=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.qe=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.od;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.te=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ue=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Fb=X(this);this.Fb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Fb.gain);this.C.start(0);this.v.connect(this.Fb);this.v.connect(this.h);this.Fb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Fb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.hc=X(this);this.fc=X(this);b=d;.01>b&&(b=.01);this.hc.gain.value=b;this.fc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.kc.curve=this.Ic;this.v.connect(this.hc);this.v.connect(this.h);this.hc.connect(this.kc);this.kc.connect(this.fc);this.fc.connect(this.i)}j(){this.v.disconnect();this.hc.disconnect();this.kc.disconnect();this.fc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ke=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.je=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Nd=new Float32Array(this.l.frequencyBinCount);this.ce=new Uint8Array(a);this.ae=this.Ya=0;b=this.u;b.Pa.add(this);T(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Ca(){this.l.getFloatFrequencyData(this.Nd);this.l.getByteTimeDomainData(this.ce);const b=this.l.fftSize;let a=this.Ya=0;for(var c=0;c<b;++c){let d=(this.ce[c]-
128)/128;0>d&&(d=-d);this.Ya<d&&(this.Ya=d);a+=d*d}c=self.eb.Fe;this.Ya=c(this.Ya);this.ae=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
